package com.example.ExpenseTracker.controllers;


import com.example.ExpenseTracker.DTOs.ExpenseParticipantDto;
import com.example.ExpenseTracker.entity.Expense;
import com.example.ExpenseTracker.entity.ExpenseParticipant;
import com.example.ExpenseTracker.entity.User;
import com.example.ExpenseTracker.services.ExpenseParticipantService;
import com.example.ExpenseTracker.services.ExpenseService;
import com.example.ExpenseTracker.services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;
import java.util.List;

//show all the expenses sent by other friends
    //
    @RestController
    @RequestMapping("/participant") //this show expense generated by the owner like you friend has set up the expense to you
    public class ExpenseParticipantController {
        @Autowired
        private ExpenseParticipantService expenseParticipantService;
        @Autowired
        private UserService userService;
        @Autowired
        private ExpenseService expenseService;
        @GetMapping("/getreq")
        public List<ExpenseParticipantDto> showingAllReceiverRequest(){
            Authentication authentication= SecurityContextHolder.getContext().getAuthentication();
            String receiverName=authentication.getName();
            List<ExpenseParticipant>list= expenseParticipantService.getAllOwedExpense(receiverName);
            List<ExpenseParticipantDto> dto=new ArrayList<>();
            for(ExpenseParticipant e:list){
                ExpenseParticipantDto d= new ExpenseParticipantDto();
                User owner= userService.findUserById(e.getOwnerId());
                Expense expense=expenseService.findExpenseByExpenseId(e.getExpenseId());

                d.setId(e.getId());
                d.setName(expense.getTitle());
                d.setOwnerName(owner.getName());
                d.setAmount(e.getAmountOwed());
                d.setImage(owner.getImageUrl());
                d.setTransactionType(e.getTransactionType());
                dto.add(d);

            }
            return dto;
        }
        //this function is for showing the owner about his generated expenses track like if participant has paid he has also a button
        //for it which is in expense service where an owner can set the expense as done for particular participant
        @GetMapping("/byEid/{expenseId}")
    public List<ExpenseParticipantDto> getParticipantByExpenseId(@PathVariable Long expenseId){
           List<ExpenseParticipant>list= expenseParticipantService.findByExpenseId(expenseId);
            List<ExpenseParticipantDto> dto=new ArrayList<>();
            for(ExpenseParticipant e:list){
                ExpenseParticipantDto d= new ExpenseParticipantDto();
                User owner= userService.findUserById(e.getOwnerId());
                User receiver= userService.findUserById(e.getUserId());
                Expense expense=expenseService.findExpenseByExpenseId(e.getExpenseId());

                d.setId(e.getId());
                d.setName(expense.getTitle());
                d.setOwnerName(owner.getName());
                d.setReceiverName(receiver.getName());
                d.setOwnerId(e.getOwnerId());
                d.setReceiverId(e.getUserId());
                d.setAmount(e.getAmountOwed());
                d.setExpenseId(e.getExpenseId());
                d.setImage(owner.getImageUrl());
                if(e.getTransactionType().equals("OWED")){
                    d.setTransactionType("PENDING");
                }else d.setTransactionType("DONE");
                dto.add(d);

            }
            return dto;
        }
    }

