package com.example.ExpenseTracker.controllers;

import com.example.ExpenseTracker.DTOs.Expense.ExpenseCreationDto;

import com.example.ExpenseTracker.DTOs.Expense.ExpenseResponseDTO;
import com.example.ExpenseTracker.entity.Expense;
import com.example.ExpenseTracker.entity.ExpenseParticipant;
import com.example.ExpenseTracker.entity.User;
import com.example.ExpenseTracker.services.ExpenseService;
import com.example.ExpenseTracker.services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

@RestController
@RequestMapping("/Expense")
public class ExpenseController {

    @Autowired
    ExpenseService expenseService;

    @Autowired
    UserService userService;


    public ExpenseResponseDTO expenseToDto(Expense expense){
        ExpenseResponseDTO dto= new ExpenseResponseDTO();
        dto.setUserId(expense.getUserId());
        dto.setAmount(expense.getAmount());
        dto.setTransactionType(expense.getTransactionType());
        dto.setTitle(expense.getTitle());
        dto.setDate(expense.getDate());
        dto.setId(expense.getId());
        return dto;
    }

    @PostMapping("/new")
    public void addExpense(@RequestBody ExpenseCreationDto dto){
        Authentication authentication=SecurityContextHolder.getContext().getAuthentication();
        String username= authentication.getName();
        expenseService.addExpense(username,dto);


    }
    //owner expenses showing up
    @GetMapping("/myexpense") //here all the expense which is generated by OWNER show up
    public List<ExpenseResponseDTO> getExpenseByUserId(){
        Authentication authentication= SecurityContextHolder.getContext().getAuthentication();
        String username = authentication.getName();
        User user = userService.findByUsername(username);


        List<ExpenseResponseDTO>dtos=new ArrayList<>();

        List<Expense>expenses= expenseService.getExpensesByUserId(user.getId());
        for(Expense expense:expenses){
            ExpenseResponseDTO exp=expenseToDto(expense);
            dtos.add(exp);
        }
        return dtos;
    }
    //owner accepting
    @PostMapping("/accept/{receiverId}/{expenseId}") //owner mark the expense done here
    public ExpenseParticipant ownerMarkingTheExpenseDone(@PathVariable Long receiverId,@PathVariable Long expenseId){
        Authentication authentication=SecurityContextHolder.getContext().getAuthentication();
        String senderName=authentication.getName();
        return expenseService.setingPaidExpense(senderName,receiverId,expenseId);
    }
    @DeleteMapping("/delete/{expenseId}")
    public void deleteExpense(@PathVariable Long expenseId){
        expenseService.deleteExpense(expenseId);
    }
}
    